"""从独立 CHANGELOG 同步本项目版本，不读取 MAS 的版本或发布配置。"""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def sync() -> None:
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    match = re.search(r"^## (\d+\.\d+\.\d+)\b", changelog, re.MULTILINE)
    if match is None:
        raise ValueError("CHANGELOG 顶部缺少独立版本号")
    version = match[1]
    metadata = ROOT / "pyproject.toml"
    text = re.sub(
        r'^version = "[^"]+"$',
        f'version = "{version}"',
        metadata.read_text(encoding="utf-8"),
        count=1,
        flags=re.MULTILINE,
    )
    metadata.write_text(text, encoding="utf-8")
    package_file = ROOT / "frontend/package.json"
    package = json.loads(package_file.read_text(encoding="utf-8"))
    package["version"] = version
    package_file.write_text(
        json.dumps(package, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (ROOT / "app/version.py").write_text(
        '# Generated by scripts/changelog.py sync.\n'
        f'VERSION = "{version}"\n',
        encoding="utf-8",
    )
    print(f"Synced standalone version {version}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["sync"])
    parser.parse_args()
    sync()
