"""从 CHANGELOG 与 changelog.d 碎片驱动版本与发版产物，不读取 MAS 的版本配置。

CHANGELOG 顶部版本段格式固定为 `## X.Y.Z（未发布|YYYY-MM-DD）`，
分类标题使用中文（新增/变更/优化/修复/安全），条目为单行 `- 内容`。
changelog.d 碎片文件名为 `<id>.<类型>.md`，类型映射到上述分类。
"""

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = ROOT / "CHANGELOG.md"
FRAGMENTS = ROOT / "changelog.d"

# 片段类型 → CHANGELOG 中文分类；CATEGORY_ORDER 决定新分类插入顺序。
CATEGORIES = {
    "feat": "新增",
    "change": "变更",
    "perf": "优化",
    "fix": "修复",
    "security": "安全",
}
CATEGORY_ORDER = ["新增", "变更", "优化", "修复", "安全"]
VERSION_LINE = re.compile(r"^## (\d+\.\d+\.\d+)（(未发布|\d{4}-\d{2}-\d{2})）\s*$")
PROJECT_NAME = "better-mas-tools"


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def parse_changelog() -> tuple[str, list[str]]:
    """返回（顶部版本号, 全部行）；找不到版本段则报错。"""
    lines = CHANGELOG.read_text(encoding="utf-8").splitlines()
    for index, line in enumerate(lines):
        if VERSION_LINE.match(line):
            return VERSION_LINE.match(line)[1], lines
    fail("CHANGELOG 顶部缺少版本段：## X.Y.Z（未发布|YYYY-MM-DD）")


def version_span(lines: list[str], version: str) -> tuple[int, int]:
    """定位指定版本的段落 [起始行, 结束行)（结束行为下一个版本行或文件尾）。"""
    start = None
    for index, line in enumerate(lines):
        match = VERSION_LINE.match(line)
        if not match:
            continue
        if match[1] == version and start is None:
            start = index
        elif start is not None:
            return start, index
    if start is None:
        fail(f"CHANGELOG 中不存在版本段 {version}")
    return start, len(lines)


def read_fragment_version(path: Path) -> str:
    parts = path.stem.split(".")
    if len(parts) < 2 or parts[-1] not in CATEGORIES:
        fail(f"碎片文件名不符合 <id>.<类型>.md 规范：{path.name}")
    return parts[-1]


def load_fragments() -> list[tuple[Path, str, str]]:
    """返回（路径, 类型, 条目文本）；单行、去掉首尾空白与列表标记。"""
    fragments = []
    for path in sorted(FRAGMENTS.glob("*.md")):
        if path.name == "README.md" or path.name.startswith("."):
            continue
        kind = read_fragment_version(path)
        text = path.read_text(encoding="utf-8").strip()
        text = re.sub(r"^-\s*", "", text)
        if "\n" in text or not text:
            fail(f"碎片内容必须为单行非空文本：{path.name}")
        fragments.append((path, kind, text))
    return fragments


def sync(version: str) -> list[str]:
    """把版本号写入全部生成物，返回被修改的文件描述列表。"""
    changed = []

    def rewrite(path: Path, pattern: str, replacement: str, label: str) -> None:
        text = path.read_text(encoding="utf-8")
        updated = re.sub(pattern, replacement, text, count=1, flags=re.M)
        if updated != text:
            path.write_text(updated, encoding="utf-8", newline="\n")
            changed.append(label)

    rewrite(
        ROOT / "pyproject.toml",
        r'^version = "[^"]+"$',
        f'version = "{version}"',
        "pyproject.toml",
    )

    package_file = ROOT / "frontend/package.json"
    package = json.loads(package_file.read_text(encoding="utf-8"))
    if package.get("version") != version:
        package["version"] = version
        package_file.write_text(
            json.dumps(package, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        changed.append("frontend/package.json")

    build_gradle = ROOT / "android/app/build.gradle.kts"
    if build_gradle.is_file():
        major, minor, patch = (int(part) for part in version.split("."))
        version_code = major * 10000 + minor * 100 + patch
        rewrite(
            build_gradle,
            r"versionCode = \d+",
            f"versionCode = {version_code}",
            "android/app/build.gradle.kts (versionCode)",
        )
        rewrite(
            build_gradle,
            r'versionName = "[^"]+"',
            f'versionName = "{version}"',
            "android/app/build.gradle.kts (versionName)",
        )

    version_py = ROOT / "app/version.py"
    expected = f'# Generated by scripts/changelog.py sync.\nVERSION = "{version}"\n'
    if version_py.read_text(encoding="utf-8") != expected:
        version_py.write_text(expected, encoding="utf-8", newline="\n")
        changed.append("app/version.py")

    uvlock = ROOT / "uv.lock"
    rewrite(
        uvlock,
        rf'(name = "{PROJECT_NAME}"\nversion = )"[\d.]+"',
        rf'\g<1>"{version}"',
        "uv.lock",
    )
    return changed


def cmd_current(_args) -> None:
    print(parse_changelog()[0])


def cmd_sync(_args) -> None:
    changed = sync(parse_changelog()[0])
    if changed:
        print("已更新：\n" + "\n".join(f"  {item}" for item in changed))
    else:
        print("各版本生成物均已同步")


def cmd_add(args) -> None:
    if args.type not in CATEGORIES:
        fail(f"未知类型 {args.type}，可选：{'/'.join(CATEGORIES)}")
    text = " ".join(args.text).strip().lstrip("- ").strip()
    if not text:
        fail("片段内容不能为空")
    identifier = args.id or datetime.now().strftime("%Y%m%d-%H%M%S")
    path = FRAGMENTS / f"{identifier}.{args.type}.md"
    if path.exists():
        fail(f"片段已存在：{path.name}（换 --id 或直接编辑）")
    if not FRAGMENTS.is_dir():
        FRAGMENTS.mkdir()
    path.write_text(text + "\n", encoding="utf-8", newline="\n")
    print(f"已创建 {path.relative_to(ROOT)}（分类：{CATEGORIES[args.type]}）")


def cmd_release(args) -> None:
    version, lines = parse_changelog()
    if version != args.version:
        fail(
            f"CHANGELOG 顶部版本为 {version}，与 --version {args.version} 不一致；"
            "请先编辑 CHANGELOG 顶部版本段"
        )
    fragments = load_fragments()
    if not fragments:
        fail("changelog.d 没有待发布片段；无变更时不需要执行 release")
    date = args.date or datetime.now().strftime("%Y-%m-%d")

    start, end = version_span(lines, version)
    segment = lines[start:end]
    # 顶部版本段写日期。
    segment[0] = f"## {version}（{date}）"
    for path, kind, text in fragments:
        category = CATEGORIES[kind]
        entry = f"- {text}"
        category_index = next(
            (i for i, line in enumerate(segment) if line.strip() == f"### {category}"),
            None,
        )
        if category_index is None:
            # 分类不存在：按 CATEGORY_ORDER 插到合适位置，找不到就追加段尾。
            priority = CATEGORY_ORDER.index(category)
            insert_at = end - start
            for offset, line in enumerate(segment[1:], start=1):
                match = re.match(r"^### (.+)$", line.strip())
                if match and match[1] in CATEGORY_ORDER:
                    if CATEGORY_ORDER.index(match[1]) > priority:
                        insert_at = offset
                        break
            segment.insert(insert_at, f"### {category}")
            insert_at += 1
            segment.insert(insert_at, "")
            insert_at += 1
            segment.insert(insert_at, entry)
        else:
            # 同分类下按文本去重后追加条目。
            boundary = next(
                (
                    i
                    for i in range(category_index + 1, len(segment))
                    if segment[i].startswith("### ")
                ),
                len(segment),
            )
            existing = {
                line.strip()
                for line in segment[category_index:boundary]
                if line.strip().startswith("- ")
            }
            if entry.strip() not in existing:
                segment.insert(boundary, entry)

    lines[start:end] = segment
    CHANGELOG.write_text(
        "\n".join(lines).rstrip("\n") + "\n", encoding="utf-8", newline="\n"
    )
    for path, _kind, _text in fragments:
        path.unlink()
    changed = sync(version)
    print(f"版本 {version}（{date}）发布内容已聚合，片段已清理。")
    print("待提交：" + "、".join(["CHANGELOG.md"] + changed))


def cmd_release_note(args) -> None:
    version = args.version or parse_changelog()[0]
    lines = CHANGELOG.read_text(encoding="utf-8").splitlines()
    start, end = version_span(lines, version)
    # Release 正文不需要重复版本标题（gh release 自带 title），从分类行起输出。
    body = [line for line in lines[start + 1 : end] if line.strip()]
    note = "\n".join(body).strip() + "\n"
    if not note.strip():
        fail(f"版本 {version} 段落没有可发布的内容")
    if args.output:
        Path(args.output).write_text(note, encoding="utf-8", newline="\n")
        print(f"Release 正文已写入 {args.output}")
    else:
        print(note, end="")


def cmd_guard(args) -> None:
    problems = []
    version, lines = parse_changelog()

    if args.tag:
        expected = f"v{version}"
        if args.tag.lstrip("v") != version:
            problems.append(
                f"tag {args.tag} 与 CHANGELOG 顶部版本 {version} 不一致（期望 {expected}）"
            )

    fragments = load_fragments()
    if fragments:
        problems.append(
            "changelog.d 存在待发布片段，需先执行 release 聚合："
            + "、".join(path.name for path, _k, _t in fragments)
        )

    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    if f'version = "{version}"' not in pyproject:
        problems.append(f"pyproject.toml 版本与 CHANGELOG（{version}）不一致，请执行 sync")
    package = json.loads((ROOT / "frontend/package.json").read_text(encoding="utf-8"))
    if package.get("version") != version:
        problems.append(f"frontend/package.json 版本与 CHANGELOG（{version}）不一致，请执行 sync")
    version_py = ROOT / "app/version.py"
    if f'VERSION = "{version}"' not in version_py.read_text(encoding="utf-8"):
        problems.append("app/version.py 版本与 CHANGELOG 不一致，请执行 sync")
    uvlock = (ROOT / "uv.lock").read_text(encoding="utf-8")
    if f'name = "{PROJECT_NAME}"\nversion = "{version}"' not in uvlock:
        problems.append("uv.lock 根包版本与 CHANGELOG 不一致，请执行 sync")
    build_gradle = ROOT / "android/app/build.gradle.kts"
    if build_gradle.is_file() and f'versionName = "{version}"' not in build_gradle.read_text(
        encoding="utf-8"
    ):
        problems.append("android versionName 与 CHANGELOG 不一致，请执行 sync")

    if problems:
        print("发布前检查未通过：", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        raise SystemExit(1)
    print(f"可以发布 {version}")


def main() -> None:
    parser = argparse.ArgumentParser(description="BMT 版本与发版产物管理")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("current", help="打印 CHANGELOG 顶部版本号").set_defaults(func=cmd_current)
    sub.add_parser("sync", help="把顶部版本号同步到全部版本生成物").set_defaults(func=cmd_sync)

    add = sub.add_parser("add", help="创建 changelog.d 碎片")
    add.add_argument("type", choices=sorted(CATEGORIES))
    add.add_argument("text", nargs="+")
    add.add_argument("--id", help="碎片文件名前缀（默认时间戳）")
    add.set_defaults(func=cmd_add)

    release = sub.add_parser("release", help="聚合碎片进顶部版本段并写日期")
    release.add_argument("--version", required=True)
    release.add_argument("--date", help="发布日期（默认今天）")
    release.set_defaults(func=cmd_release)

    note = sub.add_parser("release-note", help="输出版本段正文供 GitHub Release 使用")
    note.add_argument("--version", help="默认取顶部版本")
    note.add_argument("--output", help="写入文件而非 stdout")
    note.set_defaults(func=cmd_release_note)

    guard = sub.add_parser("guard", help="发布前守门校验")
    guard.add_argument("--tag", help="待发布的 tag（CI 传入；本地可选）")
    guard.set_defaults(func=cmd_guard)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
